### ISSUE TITLE
Movie details

### ISSUE THREAD

**Issue by Nataniel-Antosik** [Nataniel-Antosik/Bench_Project#38]
## Description

When the user enters to the app he will see a list of cards. Any card contains basic information about the film and when he clicks on any of these elements he will go to the next screen `Movie Details`.

## Endpoint: 

[link](https://developers.themoviedb.org/3/movies/get-movie-details)

## Data structure:

Movie Details:
```
    val id: Int,
    val imageBackgroundUrl: String,
    val name: String,
    val genres: List<Genres>,
    val description: String,
    val budget: Int,
    val rating: Double,
    val releaseDate: String,
    val imageUrl: String
```
Genres:
```
    val id: Int,
    val name: String

```

## Links:

https://developer.android.com/studio/write/java8-support - This could help change `relaseData` type from `String` to `LocalData`

## Tasks:

- [x] Add view model to movie details
- [x] Share movie id between fragments
- [x] Add navigator to movie details
- [x] Design UI for movie details
- [x] Add load progress indicator
