### ISSUE TITLE
Add room database

### ISSUE THREAD

**Issue by Nataniel-Antosik** [Nataniel-Antosik/Bench_Project#83]
## Description:

You can use the room database to save data from API. 

I should consider the relation between the three tables, `list movies`, `movie details`, and `genres`. 

Link: 
https://www.sqlpedia.pl/relacyjne-bazy-danych-pojecia-podstawowe/

## Database diagram

![image](https://user-images.githubusercontent.com/57491794/224535023-e716ba88-080f-4aef-989e-ea4a9fd467f5.png)

### Relations:
* One-to-one `list movies` and `movie details`
* Many-to-many `movie details` and `genres`

## Problems:
I used the relation one-to-many between `movie details` and `genres` and this approach generated issues with losing genre data. When the user has a connection with the internet he cannot see a problem. But when he enters one film, for example, the film `Avatar`, and this movie has action in genres and the next movie also has the same genres like `Avatar` it will be overridden. When the user lost connection with the internet and goes back to the movie `Avatar` he will see genres without one genre action.

Steps to reproduce:
1. Find 2 movies with one or more same genres
2. You have to connect to the internet
3. Look at the first movie after that look at the second movie
4. Disconnect from the internet
5. Back to the first movie
6. You will see fewer genres

## Tasks:

- [x] Add room database to hilt
- [x] Use database in repository popular movies
- [x] Use database in repository movie details
- [x] Use `let` instead `run` in PopularMoviesDataRepository
- [x] Delete movieDetailsFragmentNavigator
- [x] Change relation between `movie details` and `genres`
